version: "2"
linters:
  enable:
    - ginkgolinter   # https://github.com/nunnatsa/ginkgolinter
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      # https://staticcheck.dev/docs/configuration/options/#dot_import_whitelist
      dot-import-whitelist:
        # Ginkgo testsuites
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
