apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kube-rbac-proxy-tls
  creationTimestamp: null
  labels:
    control-plane: gitops-operator
  name: openshift-gitops-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    control-plane: gitops-operator
  type: ClusterIP
status:
  loadBalancer: {}
