apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: openshift-gitops-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-operator-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring