apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kube-rbac-proxy-tls
  labels:
    control-plane: gitops-operator
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    control-plane: gitops-operator
<<<<<<< HEAD
  type: ClusterIP
=======
>>>>>>> 5a223ae1212252b78662554f9836f4b72417f5a4
