# permissions for end users to edit gitopsservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsservice-editor-role
rules:
- apiGroups:
  - pipelines.openshift.io
  resources:
  - gitopsservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.openshift.io
  resources:
  - gitopsservices/status
  verbs:
  - get
