# permissions for end users to edit argocdexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notificationsconfiguration-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - notificationsconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - notificationsconfigurations/status
  verbs:
  - get