# permissions for end users to view argocdexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notificationsconfiguration-viewer-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - notificationsconfigurations
  verbs:
  - get
  - list
  - watch