apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: openshift-gitops-application-controller
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-application-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: openshift-gitops-dex-server
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-dex-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: openshift-gitops-redis-ha
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-redis-ha
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: openshift-gitops-server
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-server