apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: openshift-gitops-application-controller
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-application-controller
subjects:
- kind: ServiceAccount
  name: openshift-gitops-application-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: openshift-gitops-dex-server
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-dex-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-dex-server
subjects:
- kind: ServiceAccount
  name: openshift-gitops-dex-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: openshift-gitops-redis-ha
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-redis-ha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-redis-ha
subjects:
- kind: ServiceAccount
  name: openshift-gitops-redis-ha
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: openshift-gitops-server
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-server
subjects:
- kind: ServiceAccount
  name: openshift-gitops-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: openshift-gitops-application-controller
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-application-controller
subjects:
- kind: ServiceAccount
  name: openshift-gitops-application-controller
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: openshift-gitops-server
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-server
subjects:
- kind: ServiceAccount
  name: openshift-gitops-server
  namespace: openshift-operators