# The following patch adds a directive for openshift service ca operator to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: true
  name: argocds.argoproj.io
