{
 "title": "Overview",
 "panels": [
  {
   "title": "Clusters",
   "type": "singlestat",
   "description": "Clusters",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "singlestat",
   "description": "Applications",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "singlestat",
   "description": "Applications",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\"})"
    }
   ]
  }
 ]
}
{
 "title": "Status",
 "panels": [
  {
   "title": "Health Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  }
 ]
}
{
 "title": "Applications",
 "panels": [
  {
   "title": "Applications",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\", dest_server=~\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "Sync Stats",
 "panels": [
  {
   "title": "Sync Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Activity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval]))) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Sync Failures",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",phase=~\"Error|Failed\",dest_server=~\"$cluster\"}[$interval]))) by (namespace, phase)",
       "legendFormat": "{{phase}}: {{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}