{
 "title": "Rollouts",
 "panels": [
  {
   "title": "Uptime (controller)",
   "type": "singlestat",
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Total Rollouts",
   "type": "singlestat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Rollouts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\"}) by (strategy)"
    }
   ]
  }
 ]
}
{
 "title": "Controller Stats",
 "panels": [
  {
   "title": "Stable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{phase=\"Completed\",job=\"argo-rollouts-metrics\"} == 1)"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{phase=\"Progressing\",job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{phase=\"Paused\",job=\"argo-rollouts-metrics\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"Error\"} == 1)"
    }
   ]
  },
  {
   "title": "Invalid Spec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"InvalidSpec\"} == 1)"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"Timeout\"} == 1)"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info{job=\"argo-rollouts-metrics\",phase=\"Abort\"} == 1)"
    }
   ]
  },
  {
   "title": "Reconcile Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rollout_reconcile_count{job=\"argo-rollouts-metrics\"}[10m]))"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(rollout_reconcile_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"argo-rollouts-metrics\"}"
    }
   ]
  }
 ]
}
{
 "title": "Rollout Status",
 "panels": [
  {
   "title": "Phase",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rollout_info{job=\"argo-rollouts-metrics\",namespace=\"$namespace\",name=\"$rollout\"}"
    }
   ]
  },
  {
   "title": "Replicas (desired)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_desired{job=\"argo-rollouts-metrics\",namespace=\"$namespace\",name=\"$rollout\"}"
    }
   ]
  },
  {
   "title": "Replica (available)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_available{job=\"argo-rollouts-metrics\",namespace=\"$namespace\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Replica (unavailable)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_unavailable{job=\"argo-rollouts-metrics\",namespace=\"$namespace\",name=\"$rollout\"}"
    }
   ]
  }
 ]
}