name: KinD E2E

on:
  pull_request:
    branches:
      - "master"
      - "v*"
    paths-ignore:
      - "**/*.md"
      - "**/OWNERS"
      - "openshift-ci/**"
  push:
    branches:
      - "master"
      - "v*"
    paths-ignore:
      - "**/*.md"
      - "**/OWNERS"
      - "openshift-ci/**"

permissions:
  contents: read

jobs:
  ci-e2e-sequential:
    uses: ./.github/workflows/kind-e2e-job.yaml
    with:
      test-type: sequential

  ci-e2e-parallel:
    uses: ./.github/workflows/kind-e2e-job.yaml
    with:
      test-type: parallel
